---
# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-sample
  namespace: mysql-ns
  labels:
    app: mysql-sample
    chart: "mysql-1.6.7"
    release: "mysql-sample"
    heritage: "Helm"
type: Opaque
data:
  
  mysql-root-password:  "dGVzdGluZw=="
  
  
  
  mysql-password: "cjV2RmpPWE9DQg=="
