---
# Source: mysql/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  labels:
    app: mysql-sample
    chart: "mysql-1.6.7"
    release: "mysql-sample"
    heritage: "Helm"
