---
# Source: mysql/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-sample
  namespace: mysql-ns
  labels:
    app: mysql-sample
    chart: "mysql-1.6.7"
    release: "mysql-sample"
    heritage: "Helm"
  annotations:
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
    nodePort: 32000
  selector:
    app: mysql-sample
